spring:
  datasource:
    url: jdbc:sqlserver://victorazuredb.database.windows.net:1433;database=victorazuredb;user=victor@victorazuredb;password=Password123!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: victor
    password: Password123!
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:      ddl-auto: create-drop
            
server:  port: 9191
  

  